version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin12345
      POSTGRES_DB: resolve_mem_bot
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data