version: '3.8'

services:
  development:
    image: node:21.2.0
    build: '.'
    working_dir: /usr/app
    command: "npm run dev"
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    env_file:
      - ./.env
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CHAT_ID_TEST=-4199884334
    stdin_open: true
    tty: true
